stages:
  download:
    cmd: python src/data/download_data.py
    deps:
    - src/data/download_data.py
    outs:
    - data/raw_data/raw.csv
  split:
    cmd: python src/data/split_data.py
    deps:
    - data/raw_data/raw.csv
    - src/data/split_data.py
    outs:
    - data/processed_data/X_test.csv
    - data/processed_data/X_train.csv
    - data/processed_data/y_test.csv
    - data/processed_data/y_train.csv
  normalize:
    cmd: python src/data/normalize_data.py
    deps:
    - data/processed_data/X_test.csv
    - data/processed_data/X_train.csv
    - src/data/normalize_data.py
    outs:
    - data/processed_data/X_test_scaled.csv
    - data/processed_data/X_train_scaled.csv
    - models/scaler.pkl
  train_model:
    cmd: ./run_train.sh
    deps:
    - data/processed_data/X_train_scaled.csv
    - data/processed_data/y_train.csv
    - src/models/search_model.py
    outs:
    - models/best_model.pkl
  evaluate_model:
    cmd: ./evaluate.sh
    deps:
    - data/processed_data/X_test_scaled.csv
    - data/processed_data/y_test.csv
    - models/best_model.pkl
    - src/models/evaluate_model.py
    metrics:
    - metrics/scores.json:
        cache: false
    outs:
    - data/predictions.csv
